// Navigation Actions
export const ADVANCE_PAGE = 'ADVANCE_PAGE'
export const RECEDE_PAGE = 'RECEDE_PAGE'
export const JUMP_TO_PAGE = 'JUMP_TO_PAGE'

// Payment Actions
export const CHOOSE_CONTRIBUTION_AMOUNT = 'CHOOSE_CONTRIBUTION_AMOUNT'
export const CONFIRM_CONTRIBUTION = 'CONFIRM_CONTRIBUTION'

export const SET_EMAIL = 'SET_EMAIL'

export const SET_CREDIT_CARD_NUMBER = 'SET_CREDIT_CARD_NUMBER'
export const SET_CREDIT_CARD_EXPIRATION_DATE = 'SET_CREDIT_CARD_EXPIRATION_DATE'
export const SET_CREDIT_CARD_SECURITY_CODE = 'SET_CREDIT_CARD_SECURITY_CODE'

// Payment Field Navigation Actions
export const DID_START_EDITING_CREDIT_CARD_NUMBER = 'DID_START_EDITING_CREDIT_CARD_NUMBER'
export const DID_START_EDITING_CREDIT_CARD_EXPIRATION_DATE = 'DID_START_EDITING_CREDIT_CARD_EXPIRATION_DATE'
export const DID_START_EDITING_CREDIT_CARD_SECURITY_CODE = 'DID_START_EDITING_CREDIT_CARD_SECURITY CODE'

export const DID_FINISH_EDITING_CREDIT_CARD_NUMBER = 'DID_FINISH_EDITING_CREDIT_CARD_NUMBER'