// Navigation Actions
export const ADVANCE_PAGE = 'ADVANCE_PAGE'
export const RECEDE_PAGE = 'RECEDE_PAGE'
export const JUMP_TO_PAGE = 'JUMP_TO_PAGE'

// Payment Actions
export const CHOOSE_CONTRIBUTION_AMOUNT = 'CHOOSE_CONTRIBUTION_AMOUNT'
export const CONFIRM_CONTRIBUTION = 'CONFIRM_CONTRIBUTION'

export const SET_EMAIL = 'SET_EMAIL'

export const SET_CREDIT_CARD_NUMBER = 'SET_CREDIT_CARD_NUMBER'
export const SET_CREDIT_CARD_EXPIRATION_DATE = 'SET_CREDIT_CARD_EXPIRATION_DATE'
export const SET_CREDIT_CARD_SECURITY_CODE = 'SET_CREDIT_CARD_SECURITY_CODE'

// Payment Field Navigation Actions
export const DID_START_EDITING_CREDIT_CARD_NUMBER = 'DID_START_EDITING_CREDIT_CARD_NUMBER'
export const DID_START_EDITING_CREDIT_CARD_EXPIRATION_DATE = 'DID_START_EDITING_CREDIT_CARD_EXPIRATION_DATE'
export const DID_START_EDITING_CREDIT_CARD_SECURITY_CODE = 'DID_START_EDITING_CREDIT_CARD_SECURITY CODE'

export const DID_FINISH_EDITING_CREDIT_CARD_NUMBER = 'DID_FINISH_EDITING_CREDIT_CARD_NUMBER'

export const SET_EDITING_CREDIT_CARD_NUMBER = 'SET_EDITING_CREDIT_CARD_NUMBER'
export const SET_EDITING_CREDIT_CARD_EXPIRATION_DATE = 'SET_EDITING_CREDIT_CARD_EXPIRATION_DATE'
export const SET_EDITING_CREDIT_CARD_SECURITY_CODE = 'SET_EDITING_CREDIT_CARD_SECURITY_CODE'

export const HAS_ATTEMPTED_EMAIL_VALIDATION = 'HAS_ATTEMPTED_EMAIL_VALIDATION'

// Tokenziation Actions
export const REQUEST_PAYMENT_TOKEN = 'REQUEST_PAYMENT_TOKEN'
export const PAYMENT_TOKEN_RECEIVED = 'PAYMENT_TOKEN_RECEIVED'
export const PAYMENT_TOKEN_REQUEST_FAILED = 'PAYMENT_TOKEN_REQUEST_FAILED'

// Credit Card Error Types
export const INVALID_CREDIT_CARD_NUMBER = 'INVALID_CREDIT_CARD_NUMBER'
export const INVALID_CREDIT_CARD_EXPIRATION_MONTH = 'INVALID_CREDIT_CARD_EXPIRATION_MONTH'
export const INVALID_CREDIT_CARD_EXPIRATION_YEAR = 'INVALID_CREDIT_CARD_EXPIRATION_YEAR'
export const INVALID_CREDIT_CARD_SECURITY_CODE = 'INVALID_CREDIT_CARD_SECURITY_CODE'
export const INCORRECT_CREDIT_CARD_NUMBER = 'INCORRECT_CREDIT_CARD_NUMBER'
export const INCORRECT_CREDIT_CARD_SECURITY_CODE = 'INCORRECT_CREDIT_CARD_SECURITY_CODE'
export const EXPIRED_CREDIT_CARD = 'EXPIRED_CREDIT_CARD'
export const DECLINED_CREDIT_CARD = 'DECLINED_CREDIT_CARD'
export const UNRECOVERABLE_ERROR = 'UNRECOVERABLE_ERROR'