export const BLANK = 'BLANK'
export const INCOMPLETE = 'INCOMPLETE'
export const VALID = 'VALID'
export const INVALID = 'INVALID'
export const EXPIRED = 'EXPIRED'
export const INCORRECT = 'INCORRECT'
export const DECLINED = 'DECLINED'